= Security Properties
Markus Remplbauer
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

ifdef::backend-html5[]

link:https://quarkus.io/guides/security-properties[Security Properties]

== Dependency
[source,xml]
----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-elytron-security-properties-file</artifactId>
</dependency>
----


== Nutzen

Security für unsere API.
Endpoints können so konfiguriert werden das nur User mit bestimmten Rollen darauf zugreifen können.

== Umsetzung
=== Properties Files Realm Configuration
Die Properties Files Realm Configuration unterstützt die Zuordnung von Benutzern zu Passwörtern und von Benutzern zu Rollen.

[source,properties]
----
# Security Profiles

quarkus.http.auth.basic=true

quarkus.security.users.file.enabled=true
quarkus.security.users.file.users=test-users.properties
quarkus.security.users.file.roles=test-roles.properties
quarkus.security.users.file.realm-name=MyRealm
quarkus.security.users.file.plain-text=true
----

=== Users.properties
`Users.properties` gibt eine Klassenpfad-Ressource an, die eine Eigenschaftsdatei mit einer Benutzer-Passwort-Zuordnung ist, eine pro Zeile im Format `<username>=<password`.

[source,properties]
----
adm1n=adm1n
user=us3r
tom=pw
----

=== Roles.properties
`Roles.properties` weist dem Benutzernamen mit Comma getrennte Rollen zu.

[source,properties]
----
adm1n=admin
user=user
tom=emp
----

=== Rollen Validierung
[source,java]
----
import io.quarkus.security.identity.SecurityIdentity;
...

@GET
@Path("findAll")
@RolesAllowed({"emp", "admin"})
public Response findAllPersons() {
    return Response.ok(employeeService.findAll()).build();
}
----
<1> Nur Benutzter mit der Rolle `admin` oder der Rolle `emp` haben auf die Methode zugriff.